---
- block:
    - name: Create Docker Volume
      docker_volume:
        name: "{{ volume_name }}"
        state: present
  tags:
    - docker_volume
    - create

- block:
    - name: Destroy Docker Volume
      docker_volume:
        name: "{{ volume_name }}"
        state: absent
  tags:
    - docker_volume
    - destroy