---
pre_requisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg

docker_repo:  deb https://download.docker.com/linux/ubuntu focal stable

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

default_user_name: vagrant